name: Ubuntu-Hehe
on: 
  workflow_dispatch:
     inputs:
      auth:
        description: 'GRDP Authorization Code'
        required: true
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Creating User to Login
      run: |
         sudo useradd -m user && sudo adduser user sudo && echo 'user:preetygoodpassword:)' | sudo chpasswd
     
      # To Install different Environment replace their commands. by default it Install 'Ubuntu'
      
      # Ubuntu default will take upto 6-7 min
      # sudo apt update && sudo apt install ubuntu-desktop
      
      # For UKUI (Awesome UI) (4-5 min)
      # sudo add-apt-repository ppa:ubuntukylin-members/ukui -y && sudo apt update && sudo apt install ukui-desktop-environment
      
      # For LXDE (4 min)
      # sudo apt update && sudo apt install lxqt sddm -y
      
      # For Mate (5 min)
      # sudo apt update && sudo apt install ubuntu-mate-desktop -y
      
      # For Budgie (8 min)
      # sudo apt update && sudo apt install ubuntu-budgie-desktop -y
      
      # For KDE Plasma (10 min)
      # sudo apt update && sudo apt install tasksel && sudo tasksel install kubuntu-desktop
      
      # For Deepin (3-4 min)
      # sudo apt update && sudo add-apt-repository ppa:ubuntudde-dev/stable -y && sudo apt install ubuntudde-dde
      
      # For XFCE (2-3 min) Lite weight
      # sudo apt update && sudo apt install xfce4 && sudo chmod 777 /home/Area69Lab/
      # sudo bash -c 'echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session'

    - name: Installing Desktop Environment (wait for 5-10 min)
      run:  sudo apt update && sudo apt install ubuntu-desktop -y
    - name: Installing Google Chrome Headless
      run: |
           wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
           sudo dpkg --install google-chrome-stable_current_amd64.deb
           sudo apt install --assume-yes --fix-broken
    - name: Installing Some Configurations
      run: |
           sudo apt install nautilus expect nano -y
           sudo apt install --assume-yes xscreensaver
    - name: Installing chrome remote desktop
      run: |
           sudo apt-get update
           sudo apt-get install xbase-clients python3-psutil xvfb -y
           wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
           sudo dpkg --install chrome-remote-desktop_current_amd64.deb
           sudo apt install --assume-yes --fix-broken
    - name: generate script
      run: |
           touch setup.sh
           echo "${{ github.event.inputs.auth }}" >> "setup.sh"
           chmod 777 setup.sh
    - name: initialize GRDP
      run: |   
           expect -c '
           spawn ./setup.sh
           expect "Enter a PIN of at least six digits: "
           send "123456\r"
           expect "Enter the same PIN again: "
           send "123456\r"
           expect eof
           '
           
    - name: installing packages
      run: |
            wget https://az764295.vo.msecnd.net/stable/7f6ab5485bbc008386c4386d08766667e155244e/code_1.60.2-1632313585_amd64.deb
            sudo dpkg -i code_1.60.2-1632313585_amd64.deb
            echo 'runneradmin:preetygoodpassword:)' | sudo chpasswd
            echo 'runner:preetygoodpassword:)' | sudo chpasswd
            wget https://raw.githubusercontent.com/Mrbokri/ubuntu-hehe/main/hehe.sh
    - name: All done!
      run: bash hehe.sh
